In [1]:
from pytrends.request import TrendReq
import csv
import pandas as pd
import numpy
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
import pingouin

pytrends = TrendReq(hl='en-US', tz=360)

In [2]:
keywords = pytrends.suggestions(keyword='pepsi')#gets google trends to give a list of suggested search terms for Pepsi
df = pd.DataFrame(keywords) 
df = df.drop(columns='mid')   # This column makes no sense
pepsi_list = list(df['title'])# Converts the dataframe to a list of pepsi alternate names
pytrends.build_payload(pepsi_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='') #runs the list of alternate Pepsi names to display the google numders for each word; also allows a timeperiod for searches 
pepsi_interest_over_time_df = pytrends.interest_over_time()
pepsi_df = pepsi_interest_over_time_df.drop(columns=['PepsiCo', 'Sabyasachi Mukherjee', 'Pepsin', 'The Pepsi Bottling Group'])#Drops the colums with name suggestions that return no data
pepsi_df = pepsi_df.drop(columns="isPartial")#Drops the isspartial column that gives number where the name is partially a part of the search
pepsi_df

            Pepsi
date
2005-01-01     47
2005-02-01     61
2005-03-01     64
2005-04-01     63
2005-05-01     64
...           ...
2021-02-01     26
2021-03-01     29
2021-04-01     27
2021-05-01     29
2021-06-01     27

[198 rows x 1 columns]

In [3]:
kw_list = ['kellog']
pytrends.build_payload(kw_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
kellog_df = pytrends.interest_over_time()
kellog_df = kellog_df.drop(columns="isPartial")
kellog_df

            kellog
date
2005-01-01      96
2005-02-01      95
2005-03-01      85
2005-04-01      71
2005-05-01      85
...            ...
2021-02-01       9
2021-03-01      10
2021-04-01      11
2021-05-01      10
2021-06-01      10

[198 rows x 1 columns]

In [4]:
keywords = pytrends.suggestions(keyword='Papa John\'s')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([1,2,3,4])
papas_list = list(df['title'])
pytrends.build_payload(papas_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
papas_df = pytrends.interest_over_time()
papas_df = papas_df.drop(columns="isPartial")
papas_df

            Papa John's Pizza
date
2005-01-01                 51
2005-02-01                 41
2005-03-01                 52
2005-04-01                 43
2005-05-01                 44
...                       ...
2021-02-01                 59
2021-03-01                 47
2021-04-01                 50
2021-05-01                 50
2021-06-01                 47

[198 rows x 1 columns]

In [5]:
keywords = pytrends.suggestions(keyword='wendys')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([0,2,3])
wendys_list = list(df['title'])
pytrends.build_payload(wendys_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
wendys_df = pytrends.interest_over_time()
wendys_df = wendys_df.drop(columns="isPartial")
wendys_df

ValueError: cannot insert Wendy's, already exists

In [ ]:
keywords = pytrends.suggestions(keyword='starbucks')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([1,2,3,4])
starbucks_list = list(df['title'])
pytrends.build_payload(starbucks_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
starbucks_df = pytrends.interest_over_time()
starbucks_df = starbucks_df.drop(columns="isPartial")
starbucks_df

In [ ]:
keywords = pytrends.suggestions(keyword='comcast')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([1,2,3,4])
comcast_list = list(df['title'])
pytrends.build_payload(comcast_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
comcast_df = pytrends.interest_over_time()
comcast_df = comcast_df.drop(columns="isPartial")
comcast_df

In [ ]:
kw_list = ['Netflix']
pytrends.build_payload(kw_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
netflix_df = pytrends.interest_over_time()
netflix_df = netflix_df.drop(columns="isPartial")
netflix_df

In [ ]:
keywords = pytrends.suggestions(keyword='general motors')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([0,1,3,4])
gm_list = list(df['title'])
pytrends.build_payload(gm_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
gm_df = pytrends.interest_over_time()
gm_df = gm_df.drop(columns="isPartial")
gm_df

In [ ]:
keywords = pytrends.suggestions(keyword='uber')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([1,2,3,4])
uber_list = list(df['title'])
pytrends.build_payload(uber_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
uber_df = pytrends.interest_over_time()
uber_df = uber_df.drop(columns="isPartial")
uber_df

In [ ]:
keywords = pytrends.suggestions(keyword='walmart')
df = pd.DataFrame(keywords)
df = df.drop(columns='mid')
df = df.drop([1,2,3,4])
walmart_list = list(df['title'])
pytrends.build_payload(walmart_list, cat=0, timeframe='2005-01-01 2021-06-01', geo='', gprop='')
walmart_df = pytrends.interest_over_time()
walmart_df = walmart_df.drop(columns="isPartial")
walmart_df

In [1]:
result = pd.merge(pepsi_df, kellog_df, on="date")
result = pd.merge(result, papas_df, on="date")
result = pd.merge(result, wendys_df, on="date")
result = pd.merge(result, starbucks_df, on="date")
result = pd.merge(result, comcast_df, on="date")
result = pd.merge(result, netflix_df, on="date")
result = pd.merge(result, gm_df, on="date")
result = pd.merge(result, uber_df, on="date")
result = pd.merge(result, walmart_df, on="date") #Merges datafranes for all companies

result_headers = ['PEPSICO INC','KELLOGG CO','PAPA JOHNS INTERNATIONAL INC', 
                  "WENDY\'S CO",'STARBUCKS CORP','COMCAST CORP', 
                  'NETFLIX INC', 'GENERAL MOTORS CO','UBER TECHNOLOGIES, INC', 
                  'WALMART INC.']

result.columns = result_headers
result = result.transpose()
result

NameError: name 'pd' is not defined

In [ ]:
result.to_csv("google_trends.csv",index=True)

In [ ]:
result["ID"] = ['1','2','3','4','5','6','7','8','9','10']
result.index.name = 'name'
result = result.reset_index()
result = result.set_index(['ID', 'name'])
result